<?php
return array(
	array(
		"id" => 111,
		"sku" => "SH01",
		"parent" => "SHELTER",
		"name" => "Fossil",
		"price" => 60.20,
		"type" => "Yarn",
		"qty" => "",
		"stock" => 22,
		"img" => "https://loremflickr.com/50/50",
	),
	array(
		"id" => 112,
		"sku" => "SH02",
		"parent" => "SHELTER",
		"name" => "Woodsmoke",
		"price" => 60.20,
		"type" => "Yarn",
		"qty" => "",
		"img" => "https://loremflickr.com/50/50",
	),
	array(
		"id" => 113,
		"sku" => "SH03",
		"parent" => "SHELTER",
		"name" => "Nest",
		"price" => 60.20,
		"type" => "Yarn",
		"qty" => "",
		"img" => "https://loremflickr.com/50/50",
	),
	array(
		"id" => 114,
		"sku" => "SH04",
		"parent" => "SHELTER",
		"name" => "Pumpernickel",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 115,
		"sku" => "SH05",
		"parent" => "SHELTER",
		"name" => "Sweatshirt",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 116,
		"sku" => "SH06",
		"parent" => "SHELTER",
		"name" => "Soot",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 117,
		"sku" => "SH07",
		"parent" => "SHELTER",
		"name" => "Thistle",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 118,
		"sku" => "SH08",
		"parent" => "SHELTER",
		"name" => "Homemade Jam",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 119,
		"sku" => "SH09",
		"parent" => "SHELTER",
		"name" => "Long Johns",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1110,
		"sku" => "SH10",
		"parent" => "SHELTER",
		"name" => "Wool Socks",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1111,
		"sku" => "SH11",
		"parent" => "SHELTER",
		"name" => "Embers",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1112,
		"sku" => "SH12",
		"parent" => "SHELTER",
		"name" => "Hayloft",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1113,
		"sku" => "SH13",
		"parent" => "SHELTER",
		"name" => "Sap",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1114,
		"sku" => "SH14",
		"parent" => "SHELTER",
		"name" => "Tent",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1115,
		"sku" => "SH15",
		"parent" => "SHELTER",
		"name" => "Button Jar",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1116,
		"sku" => "SH16",
		"parent" => "SHELTER",
		"name" => "Almanac",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1117,
		"sku" => "SH17",
		"parent" => "SHELTER",
		"name" => "Faded Quilt",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1118,
		"sku" => "SH18",
		"parent" => "SHELTER",
		"name" => "Camper",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1119,
		"sku" => "SH19",
		"parent" => "SHELTER",
		"name" => "Fauna",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1120,
		"sku" => "SH20",
		"parent" => "SHELTER",
		"name" => "Foothills",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1121,
		"sku" => "SH21",
		"parent" => "SHELTER",
		"name" => "Birdbook",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1122,
		"sku" => "SH22",
		"parent" => "SHELTER",
		"name" => "Artifact",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1123,
		"sku" => "SH23",
		"parent" => "SHELTER",
		"name" => "Stormcloud",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1124,
		"sku" => "SH24",
		"parent" => "SHELTER",
		"name" => "Old World",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1125,
		"sku" => "SH25",
		"parent" => "SHELTER",
		"name" => "Plume",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1126,
		"sku" => "SH26",
		"parent" => "SHELTER",
		"name" => "Blanket Fort",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1127,
		"sku" => "SH27",
		"parent" => "SHELTER",
		"name" => "Postcard",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1128,
		"sku" => "SH28",
		"parent" => "SHELTER",
		"name" => "Barn Owl",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1129,
		"sku" => "SH29",
		"parent" => "SHELTER",
		"name" => "Truffle Hunt",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1130,
		"sku" => "SH30",
		"parent" => "SHELTER",
		"name" => "Meteorite",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1131,
		"sku" => "SH31",
		"parent" => "SHELTER",
		"name" => "Cast Iron",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1132,
		"sku" => "SH32",
		"parent" => "SHELTER",
		"name" => "Snowbound",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1133,
		"sku" => "SH33",
		"parent" => "SHELTER",
		"name" => "Tartan",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1134,
		"sku" => "SH34",
		"parent" => "SHELTER",
		"name" => "Tallow",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1135,
		"sku" => "SH35",
		"parent" => "SHELTER",
		"name" => "Cinnabar",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1136,
		"sku" => "SH36",
		"parent" => "SHELTER",
		"name" => "Bale",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1137,
		"sku" => "SH37",
		"parent" => "SHELTER",
		"name" => "Flannel",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1138,
		"sku" => "SH80",
		"parent" => "SHELTER",
		"name" => "Narwhal",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1139,
		"sku" => "SH81",
		"parent" => "SHELTER",
		"name" => "Caribou",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1140,
		"sku" => "SH82",
		"parent" => "SHELTER",
		"name" => "Newsprint",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1141,
		"sku" => "L101",
		"parent" => "LOFT",
		"name" => "Fossil",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1142,
		"sku" => "L102",
		"parent" => "LOFT",
		"name" => "Woodsmoke",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1143,
		"sku" => "L103",
		"parent" => "LOFT",
		"name" => "Nest",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1144,
		"sku" => "L104",
		"parent" => "LOFT",
		"name" => "Pumpernickel",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1145,
		"sku" => "L105",
		"parent" => "LOFT",
		"name" => "Sweatshirt",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1146,
		"sku" => "L106",
		"parent" => "LOFT",
		"name" => "Soot",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1147,
		"sku" => "L107",
		"parent" => "LOFT",
		"name" => "Thistle",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1148,
		"sku" => "L108",
		"parent" => "LOFT",
		"name" => "Homemade Jam",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1149,
		"sku" => "L109",
		"parent" => "LOFT",
		"name" => "Long Johns",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1150,
		"sku" => "L110",
		"parent" => "LOFT",
		"name" => "Wool Socks",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1151,
		"sku" => "L111",
		"parent" => "LOFT",
		"name" => "Embers",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1152,
		"sku" => "L112",
		"parent" => "LOFT",
		"name" => "Hayloft",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1153,
		"sku" => "L113",
		"parent" => "LOFT",
		"name" => "Sap",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1154,
		"sku" => "L114",
		"parent" => "LOFT",
		"name" => "Tent",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1155,
		"sku" => "L115",
		"parent" => "LOFT",
		"name" => "Button Jar",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1156,
		"sku" => "L116",
		"parent" => "LOFT",
		"name" => "Almanac",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1157,
		"sku" => "L117",
		"parent" => "LOFT",
		"name" => "Faded Quilt",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1158,
		"sku" => "L118",
		"parent" => "LOFT",
		"name" => "Camper",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1159,
		"sku" => "L119",
		"parent" => "LOFT",
		"name" => "Fauna",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1160,
		"sku" => "L120",
		"parent" => "LOFT",
		"name" => "Foothills",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1161,
		"sku" => "L121",
		"parent" => "LOFT",
		"name" => "Birdbook",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1162,
		"sku" => "L122",
		"parent" => "LOFT",
		"name" => "Artifact",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1163,
		"sku" => "L123",
		"parent" => "LOFT",
		"name" => "Stormcloud",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1164,
		"sku" => "L124",
		"parent" => "LOFT",
		"name" => "Old World",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1165,
		"sku" => "L125",
		"parent" => "LOFT",
		"name" => "Plume",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1166,
		"sku" => "L126",
		"parent" => "LOFT",
		"name" => "Blanket Fort",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1167,
		"sku" => "L127",
		"parent" => "LOFT",
		"name" => "Postcard",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1168,
		"sku" => "L128",
		"parent" => "LOFT",
		"name" => "Barn Owl",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1169,
		"sku" => "L129",
		"parent" => "LOFT",
		"name" => "Truffle Hunt",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1170,
		"sku" => "L130",
		"parent" => "LOFT",
		"name" => "Meteorite",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1171,
		"sku" => "L131",
		"parent" => "LOFT",
		"name" => "Cast Iron",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1172,
		"sku" => "L132",
		"parent" => "LOFT",
		"name" => "Snowbound",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1173,
		"sku" => "L133",
		"parent" => "LOFT",
		"name" => "Tartan",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1174,
		"sku" => "L134",
		"parent" => "LOFT",
		"name" => "Tallow",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1175,
		"sku" => "L135",
		"parent" => "LOFT",
		"name" => "Cinnabar",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1176,
		"sku" => "L136",
		"parent" => "LOFT",
		"name" => "Bale",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1177,
		"sku" => "L137",
		"parent" => "LOFT",
		"name" => "Flannel",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"id" => 1178,
		"sku" => "Q200",
		"parent" => "QUARRY",
		"name" => "Moonstone",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1179,
		"sku" => "Q205",
		"parent" => "QUARRY",
		"name" => "Geode",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1180,
		"sku" => "Q210",
		"parent" => "QUARRY",
		"name" => "Slate",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1181,
		"sku" => "Q215",
		"parent" => "QUARRY",
		"name" => "Lazulite",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1182,
		"sku" => "Q217",
		"parent" => "QUARRY",
		"name" => "Obsidian",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1183,
		"sku" => "Q220",
		"parent" => "QUARRY",
		"name" => "Serpentine",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1184,
		"sku" => "Q225",
		"parent" => "QUARRY",
		"name" => "Sulphur",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1185,
		"sku" => "Q226",
		"parent" => "QUARRY",
		"name" => "Citrine",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1186,
		"sku" => "Q230",
		"parent" => "QUARRY",
		"name" => "Hematite",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1187,
		"sku" => "Q235",
		"parent" => "QUARRY",
		"name" => "Flint",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1188,
		"sku" => "Q239",
		"parent" => "QUARRY",
		"name" => "Sandstone",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1189,
		"sku" => "Q240",
		"parent" => "QUARRY",
		"name" => "Alabaster",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1190,
		"sku" => "Q245",
		"parent" => "QUARRY",
		"name" => "Gypsum",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"id" => 1191,
		"sku" => "A405",
		"parent" => "ARBOR",
		"name" => "Morandi",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 1192,
		"sku" => "A408",
		"parent" => "ARBOR",
		"name" => "Nightfall",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 1193,
		"sku" => "A410",
		"parent" => "ARBOR",
		"name" => "Black Fig",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 1194,
		"sku" => "A413",
		"parent" => "ARBOR",
		"name" => "Cobbler",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 1195,
		"sku" => "A416",
		"parent" => "ARBOR",
		"name" => "Potion",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 1196,
		"sku" => "A419",
		"parent" => "ARBOR",
		"name" => "Vintner",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 1197,
		"sku" => "A421",
		"parent" => "ARBOR",
		"name" => "Alizarin",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 1198,
		"sku" => "A423",
		"parent" => "ARBOR",
		"name" => "Firebrush",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 1199,
		"sku" => "A426",
		"parent" => "ARBOR",
		"name" => "Butte",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11100,
		"sku" => "A433",
		"parent" => "ARBOR",
		"name" => "Tincture",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11101,
		"sku" => "A438",
		"parent" => "ARBOR",
		"name" => "Klimt",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11102,
		"sku" => "A440",
		"parent" => "ARBOR",
		"name" => "Crumb",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11103,
		"sku" => "A444",
		"parent" => "ARBOR",
		"name" => "Parka",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11104,
		"sku" => "A450",
		"parent" => "ARBOR",
		"name" => "Wreath",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11105,
		"sku" => "A455",
		"parent" => "ARBOR",
		"name" => "Rainier",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11106,
		"sku" => "A460",
		"parent" => "ARBOR",
		"name" => "Treehouse",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11107,
		"sku" => "A461",
		"parent" => "ARBOR",
		"name" => "Dorado",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11108,
		"sku" => "A466",
		"parent" => "ARBOR",
		"name" => "Sashiko",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11109,
		"sku" => "A470",
		"parent" => "ARBOR",
		"name" => "Fleet",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11110,
		"sku" => "A474",
		"parent" => "ARBOR",
		"name" => "Degas",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11111,
		"sku" => "A479",
		"parent" => "ARBOR",
		"name" => "Carob",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11112,
		"sku" => "A482",
		"parent" => "ARBOR",
		"name" => "Loam",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11113,
		"sku" => "A484",
		"parent" => "ARBOR",
		"name" => "Porter",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11114,
		"sku" => "A485",
		"parent" => "ARBOR",
		"name" => "Kettle",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11115,
		"sku" => "A487",
		"parent" => "ARBOR",
		"name" => "Humpback",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11116,
		"sku" => "A490",
		"parent" => "ARBOR",
		"name" => "Heron",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11117,
		"sku" => "A492",
		"parent" => "ARBOR",
		"name" => "Gale",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11118,
		"sku" => "A495",
		"parent" => "ARBOR",
		"name" => "Driftwood",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11119,
		"sku" => "A497",
		"parent" => "ARBOR",
		"name" => "Thaw",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11120,
		"sku" => "A499",
		"parent" => "ARBOR",
		"name" => "Hammock",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"id" => 11121,
		"sku" => "V513",
		"parent" => "VALE",
		"name" => "Cobbler",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11122,
		"sku" => "V519",
		"parent" => "VALE",
		"name" => "Vintner",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11123,
		"sku" => "V523",
		"parent" => "VALE",
		"name" => "Barberry",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11124,
		"sku" => "V524",
		"parent" => "VALE",
		"name" => "Arabesque",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11125,
		"sku" => "V538",
		"parent" => "VALE",
		"name" => "Klimt",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11126,
		"sku" => "V540",
		"parent" => "VALE",
		"name" => "Parchment",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11127,
		"sku" => "V546",
		"parent" => "VALE",
		"name" => "Vernal",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11128,
		"sku" => "V566",
		"parent" => "VALE",
		"name" => "Sashiko",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11129,
		"sku" => "V568",
		"parent" => "VALE",
		"name" => "Nocturne",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11130,
		"sku" => "V590",
		"parent" => "VALE",
		"name" => "Heron",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11131,
		"sku" => "V591",
		"parent" => "VALE",
		"name" => "Norway",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11132,
		"sku" => "V594",
		"parent" => "VALE",
		"name" => "Morel",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11133,
		"sku" => "V597",
		"parent" => "VALE",
		"name" => "Thaw",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11134,
		"sku" => "V599",
		"parent" => "VALE",
		"name" => "Hammock",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"id" => 11135,
		"sku" => "SCSL",
		"name" => "Shelter / Loft",
		"price" => 8.00,
		"parent" => "Shade Card",
		"type" => "Shade Card",
	),
	array(
		"id" => 11136,
		"sku" => "SCQ",
		"name" => "Quarry",
		"price" => 7.50,
		"parent" => "Shade Card",
		"type" => "Shade Card",
	),
	array(
		"id" => 11137,
		"sku" => "SCA",
		"name" => "Arbor",
		"price" => 8.00,
		"parent" => "Shade Card",
		"type" => "Shade Card",
	),
	array(
		"id" => 11138,
		"sku" => "SCV",
		"name" => "Vale",
		"price" => 7.50,
		"parent" => "Shade Card",
		"type" => "Shade Card",
	),
	array(
		"id" => 11139,
		"sku" => "CAP01",
		"parent" => "CAPSULE",
		"name" => "Olga Buraya-Kefelian",
		"price" => 15,
		"type" => "Books + E-Books",
	),
	array(
		"id" => 11140,
		"sku" => "CAP02",
		"parent" => "CAPSULE",
		"name" => "Michele Wang",
		"price" => 15,
		"type" => "Books + E-Books",
	),
	array(
		"id" => 11141,
		"sku" => "JJF01",
		"parent" => "WOOLENS",
		"name" => "Jared Flood",
		"price" => 15,
		"type" => "Books + E-Books",
		"qty" => "",
	),
	array(
		"id" => 11142,
		"sku" => "CARD01",
		"parent" => "SWEATER CARDS",
		"name" => "Limited Edition Watercolor",
		"price" => 10,
		"type" => "Gift Card",
	),
	array(
		"id" => 11143,
		"sku" => "P001",
		"name" => "Alberta",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11144,
		"sku" => "P002",
		"name" => "Autumn Leaves Stole",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11145,
		"sku" => "P003",
		"name" => "Beaumont",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11146,
		"sku" => "P005",
		"name" => "Brownstone",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11147,
		"sku" => "P006",
		"name" => "Celes",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11148,
		"sku" => "P007",
		"name" => "Cinder",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11149,
		"sku" => "P008",
		"name" => "Cobblestone",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11150,
		"sku" => "P009",
		"name" => "Dryad",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11151,
		"sku" => "P010",
		"name" => "Fenimore",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11152,
		"sku" => "P011",
		"name" => "Fortnight",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11153,
		"sku" => "P013",
		"name" => "Grove",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11154,
		"sku" => "P014",
		"name" => "Habitat",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11155,
		"sku" => "P016",
		"name" => "Koolhaas",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11156,
		"sku" => "P017",
		"name" => "Metropolitan",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11157,
		"sku" => "P018",
		"name" => "Pavement",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11158,
		"sku" => "P019",
		"name" => "Porom",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11159,
		"sku" => "P020",
		"name" => "Ptarmigan",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11160,
		"sku" => "P021",
		"name" => "Quincy",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11161,
		"sku" => "P023",
		"name" => "Rockaway",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11162,
		"sku" => "P024",
		"name" => "Romney Kerchief",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11163,
		"sku" => "P025",
		"name" => "Seneca",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11164,
		"sku" => "P026",
		"name" => "Setzer",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11165,
		"sku" => "P027",
		"name" => "Shale Baby Blanket",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11166,
		"sku" => "P028",
		"name" => "Stilwell",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11167,
		"sku" => "P029",
		"name" => "Turn a Square",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11168,
		"sku" => "P030",
		"name" => "Tweed Baby Blanket",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11169,
		"sku" => "P031",
		"name" => "Umaro",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11170,
		"sku" => "P032",
		"name" => "Wayfarer",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11171,
		"sku" => "P033",
		"name" => "Wee Levenwick",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11172,
		"sku" => "P034",
		"name" => "Woodruff",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11173,
		"sku" => "P035",
		"name" => "Wool Leaves",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11174,
		"sku" => "P036",
		"name" => "Acadia",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11175,
		"sku" => "P037",
		"name" => "Allegheny",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11176,
		"sku" => "P038",
		"name" => "Caldwell",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11177,
		"sku" => "P039",
		"name" => "Cyklon",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11178,
		"sku" => "P040",
		"name" => "Holl",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11179,
		"sku" => "P041",
		"name" => "Hourglass",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11180,
		"sku" => "P042",
		"name" => "Levenwick",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11181,
		"sku" => "P043",
		"name" => "Perry",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11182,
		"sku" => "P044",
		"name" => "Quinnipiac",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11183,
		"sku" => "P045",
		"name" => "Seraphine",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11184,
		"sku" => "P046",
		"name" => "Shadow",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11185,
		"sku" => "P047",
		"name" => "Shipyard",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11186,
		"sku" => "P048",
		"name" => "St. Leger",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11187,
		"sku" => "P049",
		"name" => "Sullivan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11188,
		"sku" => "P050",
		"name" => "Vega",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11189,
		"sku" => "P051",
		"name" => "Ashby",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11190,
		"sku" => "P052",
		"name" => "Bedford",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11191,
		"sku" => "P053",
		"name" => "Broome",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11192,
		"sku" => "P054",
		"name" => "Flint",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11193,
		"sku" => "P055",
		"name" => "Huxley",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11194,
		"sku" => "P056",
		"name" => "Irving",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11195,
		"sku" => "P057",
		"name" => "Lockhart",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11196,
		"sku" => "P058",
		"name" => "Muir",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11197,
		"sku" => "P059",
		"name" => "Nero",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11198,
		"sku" => "P060",
		"name" => "Ninian",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11199,
		"sku" => "P061",
		"name" => "Peabody",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11200,
		"sku" => "P062",
		"name" => "Ranger",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11201,
		"sku" => "P063",
		"name" => "Rosebud",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11202,
		"sku" => "P064",
		"name" => "Tinder",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11203,
		"sku" => "P065",
		"name" => "Topiary",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11204,
		"sku" => "P066",
		"name" => "Burnham",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11205,
		"sku" => "P067",
		"name" => "Carlisle",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11206,
		"sku" => "P068",
		"name" => "Edie",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11207,
		"sku" => "P069",
		"name" => "Farthing",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11208,
		"sku" => "P070",
		"name" => "Jaffrey",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11209,
		"sku" => "P071",
		"name" => "Leaves of Grass",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11210,
		"sku" => "P072",
		"name" => "Parson",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11211,
		"sku" => "P073",
		"name" => "Pei",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11212,
		"sku" => "P074",
		"name" => "Permafrost",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11213,
		"sku" => "P075",
		"name" => "Sakura",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11214,
		"sku" => "P076",
		"name" => "Spire",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11215,
		"sku" => "P077",
		"name" => "Stonecrop",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11216,
		"sku" => "P078",
		"name" => "Thayer",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11217,
		"sku" => "P079",
		"name" => "Wexford",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11218,
		"sku" => "P080",
		"name" => "34th & 8th",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11219,
		"sku" => "P081",
		"name" => "Arrowhead",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11220,
		"sku" => "P082",
		"name" => "Ash",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11221,
		"sku" => "P083",
		"name" => "Clemence",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11222,
		"sku" => "P084",
		"name" => "Elfreide",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11223,
		"sku" => "P085",
		"name" => "Fuse",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11224,
		"sku" => "P086",
		"name" => "Graham",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11225,
		"sku" => "P087",
		"name" => "Guston",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11226,
		"sku" => "P088",
		"name" => "Kendrick",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11227,
		"sku" => "P089",
		"name" => "Lawrence",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11228,
		"sku" => "P090",
		"name" => "Norby",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11229,
		"sku" => "P091",
		"name" => "Spruce Forest",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11230,
		"sku" => "P092",
		"name" => "Trace",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11231,
		"sku" => "P093",
		"name" => "Winnowing",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11232,
		"sku" => "P094",
		"name" => "Barrington",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11233,
		"sku" => "P095",
		"name" => "Chinook",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11234,
		"sku" => "P096",
		"name" => "Convoy",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11235,
		"sku" => "P097",
		"name" => "Exeter",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11236,
		"sku" => "P098",
		"name" => "Forester",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11237,
		"sku" => "P099",
		"name" => "Gloaming",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11238,
		"sku" => "P100",
		"name" => "Hege",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11239,
		"sku" => "P101",
		"name" => "Inversion",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11240,
		"sku" => "P102",
		"name" => "Kildare",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11241,
		"sku" => "P103",
		"name" => "Oslo",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11242,
		"sku" => "P104",
		"name" => "Polar",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11243,
		"sku" => "P105",
		"name" => "Quill",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11244,
		"sku" => "P106",
		"name" => "Ravensfoot",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11245,
		"sku" => "P107",
		"name" => "Seasons",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11246,
		"sku" => "P108",
		"name" => "Stasis",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11247,
		"sku" => "P109",
		"name" => "Sweetgrass",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11248,
		"sku" => "P110",
		"name" => "Talon",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11249,
		"sku" => "P111",
		"name" => "Ando",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11250,
		"sku" => "P112",
		"name" => "Auden",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11251,
		"sku" => "P113",
		"name" => "Bayard",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11252,
		"sku" => "P114",
		"name" => "Biston",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11253,
		"sku" => "P115",
		"name" => "Boardwalk",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11254,
		"sku" => "P116",
		"name" => "Breckon",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11255,
		"sku" => "P117",
		"name" => "Corrina",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11256,
		"sku" => "P118",
		"name" => "Edge",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11257,
		"sku" => "P119",
		"name" => "Ferrous Wrap",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11258,
		"sku" => "P120",
		"name" => "Fjord",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11259,
		"sku" => "P121",
		"name" => "Haru-Gasumi",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11260,
		"sku" => "P122",
		"name" => "Oljett",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11261,
		"sku" => "P123",
		"name" => "Reine",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11262,
		"sku" => "P124",
		"name" => "Rivage",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11263,
		"sku" => "P125",
		"name" => "Themis",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11264,
		"sku" => "P126",
		"name" => "Ticking",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11265,
		"sku" => "P127",
		"name" => "Walpole",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11266,
		"sku" => "P128",
		"name" => "Anais",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11267,
		"sku" => "P129",
		"name" => "Bowen",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11268,
		"sku" => "P130",
		"name" => "Breton",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11269,
		"sku" => "P131",
		"name" => "Burr",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11270,
		"sku" => "P132",
		"name" => "Driftwood",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11271,
		"sku" => "P133",
		"name" => "Emery",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11272,
		"sku" => "P134",
		"name" => "Eternity Cardigan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11273,
		"sku" => "P135",
		"name" => "Eternity Scarf",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11274,
		"sku" => "P136",
		"name" => "Fade",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11275,
		"sku" => "P137",
		"name" => "Fairfield",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11276,
		"sku" => "P138",
		"name" => "Gelsomina Aran",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11277,
		"sku" => "P139",
		"name" => "Gelsomina Wristwarmers",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"id" => 11278,
		"sku" => "P140",
		"name" => "Guilder",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11279,
		"sku" => "P141",
		"name" => "Hayward",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11280,
		"sku" => "P142",
		"name" => "Sempervivum",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11281,
		"sku" => "P143",
		"name" => "Turnagain",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11282,
		"sku" => "P144",
		"name" => "Wellwood",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11283,
		"sku" => "P145",
		"name" => "Benedetta",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11284,
		"sku" => "P146",
		"name" => "Chicane",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11285,
		"sku" => "P147",
		"name" => "Dresden Vest",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11286,
		"sku" => "P148",
		"name" => "Hathaway",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11287,
		"sku" => "P149",
		"name" => "Inglenook",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11288,
		"sku" => "P150",
		"name" => "Kenzo",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11289,
		"sku" => "P151",
		"name" => "Kindling",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11290,
		"sku" => "P152",
		"name" => "Lumen",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11291,
		"sku" => "P153",
		"name" => "Macallan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11292,
		"sku" => "P154",
		"name" => "Runa",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11293,
		"sku" => "P155",
		"name" => "Scrollwork",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11294,
		"sku" => "P156",
		"name" => "Stranger",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11295,
		"sku" => "P157",
		"name" => "Thorn",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11296,
		"sku" => "P158",
		"name" => "Tilda",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11297,
		"sku" => "P159",
		"name" => "Vertex",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11298,
		"sku" => "P160",
		"name" => "Adara",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11299,
		"sku" => "P161",
		"name" => "Altair",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11300,
		"sku" => "P162",
		"name" => "Clayton",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11301,
		"sku" => "P163",
		"name" => "Cypress",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11302,
		"sku" => "P164",
		"name" => "Grettir",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11303,
		"sku" => "P165",
		"name" => "Guernsey Triangle",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11304,
		"sku" => "P166",
		"name" => "Hellebore",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11305,
		"sku" => "P167",
		"name" => "Hudson",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11306,
		"sku" => "P168",
		"name" => "Ives",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11307,
		"sku" => "P169",
		"name" => "Kimmswick",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11308,
		"sku" => "P170",
		"name" => "Kirkwood",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11309,
		"sku" => "P171",
		"name" => "Knoll",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11310,
		"sku" => "P172",
		"name" => "Pinion",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11311,
		"sku" => "P173",
		"name" => "Snowflake Stole",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11312,
		"sku" => "P174",
		"name" => "Stowe",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11313,
		"sku" => "P175",
		"name" => "Tuck",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11314,
		"sku" => "P176",
		"name" => "Warren Street Cowl",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11315,
		"sku" => "P177",
		"name" => "Waterhouse",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11316,
		"sku" => "P178",
		"name" => "Amherst",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11317,
		"sku" => "P179",
		"name" => "Asilomar",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11318,
		"sku" => "P180",
		"name" => "Bolt",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11319,
		"sku" => "P181",
		"name" => "Fleur",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11320,
		"sku" => "P182",
		"name" => "Flying Squirrel",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11321,
		"sku" => "P183",
		"name" => "Frida",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11322,
		"sku" => "P184",
		"name" => "Hitch",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11323,
		"sku" => "P185",
		"name" => "Kennebec",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11324,
		"sku" => "P186",
		"name" => "Lira",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11325,
		"sku" => "P187",
		"name" => "Moon & Stars",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11326,
		"sku" => "P188",
		"name" => "Reverb",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11327,
		"sku" => "P189",
		"name" => "Sandness",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11328,
		"sku" => "P190",
		"name" => "Sandycove",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11329,
		"sku" => "P191",
		"name" => "Stones & Stripes",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11330,
		"sku" => "P192",
		"name" => "Tilt",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11331,
		"sku" => "P193",
		"name" => "Wheaten",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11332,
		"sku" => "P194",
		"name" => "Barrett",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11333,
		"sku" => "P195",
		"name" => "Brig",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11334,
		"sku" => "P196",
		"name" => "Chesterfield",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11335,
		"sku" => "P197",
		"name" => "Eno",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11336,
		"sku" => "P198",
		"name" => "Fort",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11337,
		"sku" => "P199",
		"name" => "Hayes",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11338,
		"sku" => "P200",
		"name" => "Hugo",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11339,
		"sku" => "P201",
		"name" => "Janzen",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11340,
		"sku" => "P202",
		"name" => "Quay",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11341,
		"sku" => "P203",
		"name" => "Redford",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11342,
		"sku" => "P204",
		"name" => "Slade",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11343,
		"sku" => "P205",
		"name" => "Squall",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11344,
		"sku" => "P206",
		"name" => "Timberline",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"id" => 11345,
		"sku" => "P207",
		"name" => "Afton",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11346,
		"sku" => "P208",
		"name" => "Archer",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11347,
		"sku" => "P209",
		"name" => "Bray Cap",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11348,
		"sku" => "P210",
		"name" => "Bray Pullover",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11349,
		"sku" => "P211",
		"name" => "Coal Cardigan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11350,
		"sku" => "P212",
		"name" => "Feather",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11351,
		"sku" => "P213",
		"name" => "Hartford",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11352,
		"sku" => "P214",
		"name" => "Idlewild",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11353,
		"sku" => "P215",
		"name" => "Jules",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11354,
		"sku" => "P216",
		"name" => "Oshima",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11355,
		"sku" => "P217",
		"name" => "Stonecutter",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11356,
		"sku" => "P218",
		"name" => "Tread",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11357,
		"sku" => "P219",
		"name" => "Trillium",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11358,
		"sku" => "P220",
		"name" => "Vale",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11359,
		"sku" => "P221",
		"name" => "Bough",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11360,
		"sku" => "P222",
		"name" => "Brigitte",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11361,
		"sku" => "P223",
		"name" => "Carpino",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11362,
		"sku" => "P224",
		"name" => "Ceridwen",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11363,
		"sku" => "P225",
		"name" => "Gentian",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11364,
		"sku" => "P226",
		"name" => "Greenwood",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11365,
		"sku" => "P227",
		"name" => "Little Wave",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11366,
		"sku" => "P228",
		"name" => "Persimmon",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11367,
		"sku" => "P229",
		"name" => "Rook",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11368,
		"sku" => "P230",
		"name" => "Sundottir",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11369,
		"sku" => "P231",
		"name" => "Svalbard",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11370,
		"sku" => "P232",
		"name" => "Tree Rings",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11371,
		"sku" => "P233",
		"name" => "Trestle",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11372,
		"sku" => "P234",
		"name" => "Abbott",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11373,
		"sku" => "P235",
		"name" => "Alloy",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11374,
		"sku" => "P236",
		"name" => "Benton",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11375,
		"sku" => "P237",
		"name" => "Channel Cardigan",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11376,
		"sku" => "P238",
		"name" => "Echelon",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11377,
		"sku" => "P239",
		"name" => "Elmont",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11378,
		"sku" => "P240",
		"name" => "Frieze",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11379,
		"sku" => "P241",
		"name" => "Hickory Cap",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11380,
		"sku" => "P242",
		"name" => "Kelpie",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11381,
		"sku" => "P243",
		"name" => "Landfall",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11382,
		"sku" => "P244",
		"name" => "Montauk",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11383,
		"sku" => "P245",
		"name" => "Nord",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11384,
		"sku" => "P246",
		"name" => "Portis",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11385,
		"sku" => "P247",
		"name" => "Thicket",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11386,
		"sku" => "P248",
		"name" => "Walsh",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11387,
		"sku" => "P249",
		"name" => "Arabella",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11388,
		"sku" => "P250",
		"name" => "Arvid",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11389,
		"sku" => "P251",
		"name" => "Coda",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11390,
		"sku" => "P252",
		"name" => "Devlan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11391,
		"sku" => "P253",
		"name" => "Halligarth",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11392,
		"sku" => "P254",
		"name" => "Hoquiam",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11393,
		"sku" => "P255",
		"name" => "Ivar",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11394,
		"sku" => "P256",
		"name" => "Merle",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11395,
		"sku" => "P257",
		"name" => "Natsumi",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11396,
		"sku" => "P258",
		"name" => "Nimbus",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11397,
		"sku" => "P259",
		"name" => "Pente",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11398,
		"sku" => "P260",
		"name" => "Seacoast",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11399,
		"sku" => "P261",
		"name" => "Seine",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11400,
		"sku" => "P262",
		"name" => "Vector",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11401,
		"sku" => "P263",
		"name" => "Yane",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11402,
		"sku" => "P264",
		"name" => "Arlo",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11403,
		"sku" => "P265",
		"name" => "Atlas",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11404,
		"sku" => "P266",
		"name" => "Bairn",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11405,
		"sku" => "P267",
		"name" => "Berenice",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11406,
		"sku" => "P268",
		"name" => "Carson",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11407,
		"sku" => "P269",
		"name" => "Humphrey",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11408,
		"sku" => "P270",
		"name" => "Husk",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11409,
		"sku" => "P271",
		"name" => "Magnus",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11410,
		"sku" => "P272",
		"name" => "Petal",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11411,
		"sku" => "P273",
		"name" => "Pinwheel",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11412,
		"sku" => "P274",
		"name" => "Sock Monkey",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11413,
		"sku" => "P275",
		"name" => "Spore",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11414,
		"sku" => "P276",
		"name" => "Vika",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11415,
		"sku" => "P277",
		"name" => "Winslow",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11416,
		"sku" => "P278",
		"name" => "Wyatt",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11417,
		"sku" => "P279",
		"name" => "Backbay",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11418,
		"sku" => "P280",
		"name" => "Bellows",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11419,
		"sku" => "P281",
		"name" => "Crosby",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11420,
		"sku" => "P282",
		"name" => "Docklight",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11421,
		"sku" => "P283",
		"name" => "Furl",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11422,
		"sku" => "P284",
		"name" => "Hawser",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11423,
		"sku" => "P285",
		"name" => "Hutchin",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11424,
		"sku" => "P286",
		"name" => "Ludlow",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11425,
		"sku" => "P287",
		"name" => "Ondawa",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11426,
		"sku" => "P288",
		"name" => "Rowe",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11427,
		"sku" => "P289",
		"name" => "Shackleton",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11428,
		"sku" => "P290",
		"name" => "Skiff",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11429,
		"sku" => "P291",
		"name" => "Spinnaker",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11430,
		"sku" => "P292",
		"name" => "Tiller",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11431,
		"sku" => "P293",
		"name" => "Wake",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11432,
		"sku" => "P294",
		"name" => "Zenith",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11433,
		"sku" => "P295",
		"name" => "Aster",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11434,
		"sku" => "P296",
		"name" => "Bracondale",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11435,
		"sku" => "P297",
		"name" => "Cedarwood",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11436,
		"sku" => "P298",
		"name" => "Corbara",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11437,
		"sku" => "P299",
		"name" => "Eaves",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11438,
		"sku" => "P300",
		"name" => "Escher",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11439,
		"sku" => "P301",
		"name" => "Field",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11440,
		"sku" => "P302",
		"name" => "Flight",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11441,
		"sku" => "P303",
		"name" => "Gable",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11442,
		"sku" => "P304",
		"name" => "Keel",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11443,
		"sku" => "P305",
		"name" => "Maurits",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11444,
		"sku" => "P306",
		"name" => "Millisande",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11445,
		"sku" => "P307",
		"name" => "Rambler",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11446,
		"sku" => "P308",
		"name" => "Sawmill River",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11447,
		"sku" => "P309",
		"name" => "Skew",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11448,
		"sku" => "P310",
		"name" => "Stratum",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11449,
		"sku" => "P311",
		"name" => "Woodfords",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11450,
		"sku" => "P312",
		"name" => "Agnes",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11451,
		"sku" => "P313",
		"name" => "Alvy",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11452,
		"sku" => "P314",
		"name" => "Carpeaux",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11453,
		"sku" => "P315",
		"name" => "Chainlink",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11454,
		"sku" => "P316",
		"name" => "Cordova",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11455,
		"sku" => "P317",
		"name" => "Emerson",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11456,
		"sku" => "P318",
		"name" => "Harper",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11457,
		"sku" => "P319",
		"name" => "Keaton",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11458,
		"sku" => "P320",
		"name" => "Kusama",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11459,
		"sku" => "P321",
		"name" => "Lexington",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11460,
		"sku" => "P322",
		"name" => "Marshal",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11461,
		"sku" => "P323",
		"name" => "Midway",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11462,
		"sku" => "P324",
		"name" => "Nomad",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11463,
		"sku" => "P325",
		"name" => "Sanford",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11464,
		"sku" => "P326",
		"name" => "Shui-Mo",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11465,
		"sku" => "P327",
		"name" => "Tapestry",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11466,
		"sku" => "P328",
		"name" => "Yishu",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11467,
		"sku" => "P329",
		"name" => "Albion",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11468,
		"sku" => "P330",
		"name" => "Bradbury",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11469,
		"sku" => "P331",
		"name" => "Carbon",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11470,
		"sku" => "P332",
		"name" => "Crag",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11471,
		"sku" => "P333",
		"name" => "Denali",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11472,
		"sku" => "P334",
		"name" => "Dunaway",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11473,
		"sku" => "P335",
		"name" => "Jackdaw",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11474,
		"sku" => "P336",
		"name" => "Longfellow",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11475,
		"sku" => "P337",
		"name" => "Oshima (for Him",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11476,
		"sku" => "P338",
		"name" => "Rift",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"id" => 11477,
		"sku" => "P339",
		"name" => "Sawyer",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11478,
		"sku" => "P340",
		"name" => "Shield",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11479,
		"sku" => "P341",
		"name" => "Snare",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11480,
		"sku" => "P342",
		"name" => "Anisos",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11481,
		"sku" => "P343",
		"name" => "Arbre",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11482,
		"sku" => "P344",
		"name" => "Element",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11483,
		"sku" => "P345",
		"name" => "Gehry",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11484,
		"sku" => "P346",
		"name" => "Grille",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11485,
		"sku" => "P347",
		"name" => "Gyre",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11486,
		"sku" => "P348",
		"name" => "Imago",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11487,
		"sku" => "P349",
		"name" => "Kea",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11488,
		"sku" => "P350",
		"name" => "Koto",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11489,
		"sku" => "P351",
		"name" => "Loden",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11490,
		"sku" => "P352",
		"name" => "Mimic",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11491,
		"sku" => "P353",
		"name" => "Mirepoix",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11492,
		"sku" => "P354",
		"name" => "Rakke",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11493,
		"sku" => "P355",
		"name" => "Truss",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11494,
		"sku" => "P356",
		"name" => "Ashland",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11495,
		"sku" => "P357",
		"name" => "Bannock",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11496,
		"sku" => "P358",
		"name" => "Birch Bay",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11497,
		"sku" => "P359",
		"name" => "Cascades",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11498,
		"sku" => "P360",
		"name" => "Copse",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11499,
		"sku" => "P361",
		"name" => "Deschutes",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11500,
		"sku" => "P362",
		"name" => "Fletching",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11501,
		"sku" => "P363",
		"name" => "Lander",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11502,
		"sku" => "P364",
		"name" => "Lolo",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11503,
		"sku" => "P365",
		"name" => "McLoughlin",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11504,
		"sku" => "P366",
		"name" => "Nehalem",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11505,
		"sku" => "P367",
		"name" => "Riverbend",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11506,
		"sku" => "P368",
		"name" => "Sauvie",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11507,
		"sku" => "P369",
		"name" => "Trailhead",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11508,
		"sku" => "P370",
		"name" => "Willamette",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11509,
		"sku" => "P371",
		"name" => "Bauhin",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11510,
		"sku" => "P372",
		"name" => "Breaker",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11511,
		"sku" => "P373",
		"name" => "Cadence",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11512,
		"sku" => "P374",
		"name" => "Corvid",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11513,
		"sku" => "P375",
		"name" => "Halus",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11514,
		"sku" => "P376",
		"name" => "Intersect",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11515,
		"sku" => "P377",
		"name" => "League",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11516,
		"sku" => "P378",
		"name" => "Lohman",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11517,
		"sku" => "P380",
		"name" => "Oxbow",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11518,
		"sku" => "P381",
		"name" => "Riptide",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11519,
		"sku" => "P382",
		"name" => "Roslyn",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11520,
		"sku" => "P383",
		"name" => "Selune",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11521,
		"sku" => "P384",
		"name" => "Snoqualmie",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11522,
		"sku" => "P385",
		"name" => "Tallis",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11523,
		"sku" => "P386",
		"name" => "Vela",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11524,
		"sku" => "P387",
		"name" => "Breslin",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11525,
		"sku" => "P388",
		"name" => "Caspian",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11526,
		"sku" => "P389",
		"name" => "Fairweather",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11527,
		"sku" => "P390",
		"name" => "Forge",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11528,
		"sku" => "P391",
		"name" => "Larus",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11529,
		"sku" => "P392",
		"name" => "Vanora",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11530,
		"sku" => "P393",
		"name" => "Amarilli",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11531,
		"sku" => "P394",
		"name" => "Aquinnah",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11532,
		"sku" => "P395",
		"name" => "Bronwyn",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"id" => 11533,
		"sku" => "P396",
		"name" => "Haro",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11534,
		"sku" => "P397",
		"name" => "Kierson",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11535,
		"sku" => "P398",
		"name" => "Loess",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11536,
		"sku" => "P399",
		"name" => "Lorient",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11537,
		"sku" => "P400",
		"name" => "Lunette",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11538,
		"sku" => "P401",
		"name" => "Marylebone",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11539,
		"sku" => "P402",
		"name" => "Migration",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11540,
		"sku" => "P403",
		"name" => "Oda",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11541,
		"sku" => "P404",
		"name" => "Rigel",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11542,
		"sku" => "P405",
		"name" => "Saiph",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11543,
		"sku" => "P406",
		"name" => "Scalene",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"id" => 11544,
		"sku" => "P407",
		"name" => "Valemont",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11545,
		"sku" => "P408",
		"name" => "Auster - Men\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11546,
		"sku" => "P409",
		"name" => "Auster - Women’s",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11547,
		"sku" => "P410",
		"name" => "Brighton - Men\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11548,
		"sku" => "P411",
		"name" => "Brighton - Women\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11549,
		"sku" => "P412",
		"name" => "Carver - Men\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11550,
		"sku" => "P413",
		"name" => "Carver - Women’s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11551,
		"sku" => "P414",
		"name" => "Cricket - Men\'s",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11552,
		"sku" => "P415",
		"name" => "Cricket - Women\'s",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11553,
		"sku" => "P416",
		"name" => "Mawson",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11554,
		"sku" => "P417",
		"name" => "Mohr - Men\'s",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11555,
		"sku" => "P418",
		"name" => "Mohr - Women\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11556,
		"sku" => "P419",
		"name" => "Pavo",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11557,
		"sku" => "P420",
		"name" => "Spearheads",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11558,
		"sku" => "P421",
		"name" => "Tamarack - Men’s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11559,
		"sku" => "P422",
		"name" => "Tamarack - Women\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11560,
		"sku" => "P423",
		"name" => "Vika (for Adults",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11561,
		"sku" => "P424",
		"name" => "Burnaby Hat",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11562,
		"sku" => "P425",
		"name" => "Burnaby Shawl",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11563,
		"sku" => "P426",
		"name" => "Foundry",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11564,
		"sku" => "P427",
		"name" => "Guernsey Wrap",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11565,
		"sku" => "P428",
		"name" => "High Pines Cowl",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11566,
		"sku" => "P429",
		"name" => "Hirombe",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11567,
		"sku" => "P430",
		"name" => "Junction",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11568,
		"sku" => "P431",
		"name" => "Laurel",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11569,
		"sku" => "P432",
		"name" => "Terra",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11570,
		"sku" => "P433",
		"name" => "Binary",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11571,
		"sku" => "P434",
		"name" => "Counterpane",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"id" => 11572,
		"sku" => "P435",
		"name" => "Hilt",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11573,
		"sku" => "P436",
		"name" => "Kirwin",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11574,
		"sku" => "P437",
		"name" => "Lancet",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11575,
		"sku" => "P438",
		"name" => "Mei",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11576,
		"sku" => "P439",
		"name" => "Nila",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11577,
		"sku" => "P440",
		"name" => "Oban",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11578,
		"sku" => "P441",
		"name" => "Prime",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11579,
		"sku" => "P442",
		"name" => "Proof Hat",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11580,
		"sku" => "P443",
		"name" => "Proof Scarf",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11581,
		"sku" => "P444",
		"name" => "Rivage Coat",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11582,
		"sku" => "P445",
		"name" => "Shoji",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11583,
		"sku" => "P446",
		"name" => "Stonehaven",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11584,
		"sku" => "P447",
		"name" => "Svenson",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"id" => 11585,
		"sku" => "P448",
		"name" => "Toulouse",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11586,
		"sku" => "P449",
		"name" => "Atlas",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11587,
		"sku" => "P450",
		"name" => "Frostpeak",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"id" => 11588,
		"sku" => "P451",
		"name" => "Morse",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11589,
		"sku" => "P452",
		"name" => "Pyry",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11590,
		"sku" => "P453",
		"name" => "Schulz",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11591,
		"sku" => "P454",
		"name" => "Townes",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"id" => 11592,
		"sku" => "P455",
		"name" => "Tundra",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11593,
		"sku" => "P456",
		"name" => "Bridgewater",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11594,
		"sku" => "P457",
		"name" => "Girasole",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11595,
		"sku" => "P458",
		"name" => "Lucca",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11596,
		"sku" => "P459",
		"name" => "Rock Island",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11597,
		"sku" => "P460",
		"name" => "Juneberry",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11598,
		"sku" => "P461",
		"name" => "Gully (available July 1",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11599,
		"sku" => "P462",
		"name" => "Akiko",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11600,
		"sku" => "P463",
		"name" => "Bell",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11601,
		"sku" => "P464",
		"name" => "Boundary",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11602,
		"sku" => "P465",
		"name" => "Divide",
		"price" => 12,
		"type" => "Pattern",
	),
	array(
		"id" => 11603,
		"sku" => "P466",
		"name" => "Harlowe",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11604,
		"sku" => "P467",
		"name" => "Leadlight",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11605,
		"sku" => "P468",
		"name" => "Level",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11606,
		"sku" => "P469",
		"name" => "Mossbank",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"id" => 11607,
		"sku" => "P470",
		"name" => "Prism",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11608,
		"sku" => "P471",
		"name" => "Ravine",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"id" => 11609,
		"sku" => "P472",
		"name" => "Rivet",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"id" => 11610,
		"sku" => "P473",
		"name" => "Ronan",
		"price" => 6,
		"type" => "Pattern",
	),
);
