<?php
return array(
	array(
		"sku" => "SH01",
		"parent" => "SHELTER",
		"name" => "Fossil",
		"price" => 60.20,
		"type" => "Yarn",
		"qty" => "",
		"stock" => 22,
		"img" => "https://loremflickr.com/50/50",
	),
	array(
		"sku" => "SH02",
		"parent" => "SHELTER",
		"name" => "Woodsmoke",
		"price" => 60.20,
		"type" => "Yarn",
		"qty" => "",
		"img" => "https://loremflickr.com/50/50",
	),
	array(
		"sku" => "SH03",
		"parent" => "SHELTER",
		"name" => "Nest",
		"price" => 60.20,
		"type" => "Yarn",
		"qty" => "",
		"img" => "https://loremflickr.com/50/50",
	),
	array(
		"sku" => "SH04",
		"parent" => "SHELTER",
		"name" => "Pumpernickel",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH05",
		"parent" => "SHELTER",
		"name" => "Sweatshirt",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH06",
		"parent" => "SHELTER",
		"name" => "Soot",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH07",
		"parent" => "SHELTER",
		"name" => "Thistle",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH08",
		"parent" => "SHELTER",
		"name" => "Homemade Jam",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH09",
		"parent" => "SHELTER",
		"name" => "Long Johns",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH10",
		"parent" => "SHELTER",
		"name" => "Wool Socks",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH11",
		"parent" => "SHELTER",
		"name" => "Embers",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH12",
		"parent" => "SHELTER",
		"name" => "Hayloft",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH13",
		"parent" => "SHELTER",
		"name" => "Sap",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH14",
		"parent" => "SHELTER",
		"name" => "Tent",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH15",
		"parent" => "SHELTER",
		"name" => "Button Jar",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH16",
		"parent" => "SHELTER",
		"name" => "Almanac",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH17",
		"parent" => "SHELTER",
		"name" => "Faded Quilt",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH18",
		"parent" => "SHELTER",
		"name" => "Camper",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH19",
		"parent" => "SHELTER",
		"name" => "Fauna",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH20",
		"parent" => "SHELTER",
		"name" => "Foothills",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH21",
		"parent" => "SHELTER",
		"name" => "Birdbook",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH22",
		"parent" => "SHELTER",
		"name" => "Artifact",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH23",
		"parent" => "SHELTER",
		"name" => "Stormcloud",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH24",
		"parent" => "SHELTER",
		"name" => "Old World",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH25",
		"parent" => "SHELTER",
		"name" => "Plume",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH26",
		"parent" => "SHELTER",
		"name" => "Blanket Fort",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH27",
		"parent" => "SHELTER",
		"name" => "Postcard",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH28",
		"parent" => "SHELTER",
		"name" => "Barn Owl",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH29",
		"parent" => "SHELTER",
		"name" => "Truffle Hunt",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH30",
		"parent" => "SHELTER",
		"name" => "Meteorite",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH31",
		"parent" => "SHELTER",
		"name" => "Cast Iron",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH32",
		"parent" => "SHELTER",
		"name" => "Snowbound",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH33",
		"parent" => "SHELTER",
		"name" => "Tartan",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH34",
		"parent" => "SHELTER",
		"name" => "Tallow",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH35",
		"parent" => "SHELTER",
		"name" => "Cinnabar",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH36",
		"parent" => "SHELTER",
		"name" => "Bale",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH37",
		"parent" => "SHELTER",
		"name" => "Flannel",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH80",
		"parent" => "SHELTER",
		"name" => "Narwhal",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH81",
		"parent" => "SHELTER",
		"name" => "Caribou",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "SH82",
		"parent" => "SHELTER",
		"name" => "Newsprint",
		"price" => 60.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L101",
		"parent" => "LOFT",
		"name" => "Fossil",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L102",
		"parent" => "LOFT",
		"name" => "Woodsmoke",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L103",
		"parent" => "LOFT",
		"name" => "Nest",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L104",
		"parent" => "LOFT",
		"name" => "Pumpernickel",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L105",
		"parent" => "LOFT",
		"name" => "Sweatshirt",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L106",
		"parent" => "LOFT",
		"name" => "Soot",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L107",
		"parent" => "LOFT",
		"name" => "Thistle",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L108",
		"parent" => "LOFT",
		"name" => "Homemade Jam",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L109",
		"parent" => "LOFT",
		"name" => "Long Johns",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L110",
		"parent" => "LOFT",
		"name" => "Wool Socks",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L111",
		"parent" => "LOFT",
		"name" => "Embers",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L112",
		"parent" => "LOFT",
		"name" => "Hayloft",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L113",
		"parent" => "LOFT",
		"name" => "Sap",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L114",
		"parent" => "LOFT",
		"name" => "Tent",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L115",
		"parent" => "LOFT",
		"name" => "Button Jar",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L116",
		"parent" => "LOFT",
		"name" => "Almanac",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L117",
		"parent" => "LOFT",
		"name" => "Faded Quilt",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L118",
		"parent" => "LOFT",
		"name" => "Camper",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L119",
		"parent" => "LOFT",
		"name" => "Fauna",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L120",
		"parent" => "LOFT",
		"name" => "Foothills",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L121",
		"parent" => "LOFT",
		"name" => "Birdbook",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L122",
		"parent" => "LOFT",
		"name" => "Artifact",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L123",
		"parent" => "LOFT",
		"name" => "Stormcloud",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L124",
		"parent" => "LOFT",
		"name" => "Old World",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L125",
		"parent" => "LOFT",
		"name" => "Plume",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L126",
		"parent" => "LOFT",
		"name" => "Blanket Fort",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L127",
		"parent" => "LOFT",
		"name" => "Postcard",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L128",
		"parent" => "LOFT",
		"name" => "Barn Owl",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L129",
		"parent" => "LOFT",
		"name" => "Truffle Hunt",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L130",
		"parent" => "LOFT",
		"name" => "Meteorite",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L131",
		"parent" => "LOFT",
		"name" => "Cast Iron",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L132",
		"parent" => "LOFT",
		"name" => "Snowbound",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L133",
		"parent" => "LOFT",
		"name" => "Tartan",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L134",
		"parent" => "LOFT",
		"name" => "Tallow",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L135",
		"parent" => "LOFT",
		"name" => "Cinnabar",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L136",
		"parent" => "LOFT",
		"name" => "Bale",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "L137",
		"parent" => "LOFT",
		"name" => "Flannel",
		"price" => 70.20,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q200",
		"parent" => "QUARRY",
		"name" => "Moonstone",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q205",
		"parent" => "QUARRY",
		"name" => "Geode",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q210",
		"parent" => "QUARRY",
		"name" => "Slate",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q215",
		"parent" => "QUARRY",
		"name" => "Lazulite",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q217",
		"parent" => "QUARRY",
		"name" => "Obsidian",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q220",
		"parent" => "QUARRY",
		"name" => "Serpentine",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q225",
		"parent" => "QUARRY",
		"name" => "Sulphur",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q226",
		"parent" => "QUARRY",
		"name" => "Citrine",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q230",
		"parent" => "QUARRY",
		"name" => "Hematite",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q235",
		"parent" => "QUARRY",
		"name" => "Flint",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q239",
		"parent" => "QUARRY",
		"name" => "Sandstone",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q240",
		"parent" => "QUARRY",
		"name" => "Alabaster",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "Q245",
		"parent" => "QUARRY",
		"name" => "Gypsum",
		"price" => 53.58,
		"type" => "Yarn",
	),
	array(
		"sku" => "A405",
		"parent" => "ARBOR",
		"name" => "Morandi",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A408",
		"parent" => "ARBOR",
		"name" => "Nightfall",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A410",
		"parent" => "ARBOR",
		"name" => "Black Fig",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A413",
		"parent" => "ARBOR",
		"name" => "Cobbler",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A416",
		"parent" => "ARBOR",
		"name" => "Potion",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A419",
		"parent" => "ARBOR",
		"name" => "Vintner",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A421",
		"parent" => "ARBOR",
		"name" => "Alizarin",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A423",
		"parent" => "ARBOR",
		"name" => "Firebrush",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A426",
		"parent" => "ARBOR",
		"name" => "Butte",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A433",
		"parent" => "ARBOR",
		"name" => "Tincture",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A438",
		"parent" => "ARBOR",
		"name" => "Klimt",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A440",
		"parent" => "ARBOR",
		"name" => "Crumb",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A444",
		"parent" => "ARBOR",
		"name" => "Parka",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A450",
		"parent" => "ARBOR",
		"name" => "Wreath",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A455",
		"parent" => "ARBOR",
		"name" => "Rainier",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A460",
		"parent" => "ARBOR",
		"name" => "Treehouse",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A461",
		"parent" => "ARBOR",
		"name" => "Dorado",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A466",
		"parent" => "ARBOR",
		"name" => "Sashiko",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A470",
		"parent" => "ARBOR",
		"name" => "Fleet",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A474",
		"parent" => "ARBOR",
		"name" => "Degas",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A479",
		"parent" => "ARBOR",
		"name" => "Carob",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A482",
		"parent" => "ARBOR",
		"name" => "Loam",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A484",
		"parent" => "ARBOR",
		"name" => "Porter",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A485",
		"parent" => "ARBOR",
		"name" => "Kettle",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A487",
		"parent" => "ARBOR",
		"name" => "Humpback",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A490",
		"parent" => "ARBOR",
		"name" => "Heron",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A492",
		"parent" => "ARBOR",
		"name" => "Gale",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A495",
		"parent" => "ARBOR",
		"name" => "Driftwood",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A497",
		"parent" => "ARBOR",
		"name" => "Thaw",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "A499",
		"parent" => "ARBOR",
		"name" => "Hammock",
		"price" => 63.10,
		"type" => "Yarn",
	),
	array(
		"sku" => "V513",
		"parent" => "VALE",
		"name" => "Cobbler",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V519",
		"parent" => "VALE",
		"name" => "Vintner",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V523",
		"parent" => "VALE",
		"name" => "Barberry",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V524",
		"parent" => "VALE",
		"name" => "Arabesque",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V538",
		"parent" => "VALE",
		"name" => "Klimt",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V540",
		"parent" => "VALE",
		"name" => "Parchment",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V546",
		"parent" => "VALE",
		"name" => "Vernal",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V566",
		"parent" => "VALE",
		"name" => "Sashiko",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V568",
		"parent" => "VALE",
		"name" => "Nocturne",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V590",
		"parent" => "VALE",
		"name" => "Heron",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V591",
		"parent" => "VALE",
		"name" => "Norway",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V594",
		"parent" => "VALE",
		"name" => "Morel",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V597",
		"parent" => "VALE",
		"name" => "Thaw",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "V599",
		"parent" => "VALE",
		"name" => "Hammock",
		"price" => 65.50,
		"type" => "Yarn",
	),
	array(
		"sku" => "SCSL",
		"name" => "Shelter / Loft",
		"price" => 8.00,
		"parent" => "Shade Card",
		"type" => "Shade Card",
	),
	array(
		"sku" => "SCQ",
		"name" => "Quarry",
		"price" => 7.50,
		"parent" => "Shade Card",
		"type" => "Shade Card",
	),
	array(
		"sku" => "SCA",
		"name" => "Arbor",
		"price" => 8.00,
		"parent" => "Shade Card",
		"type" => "Shade Card",
	),
	array(
		"sku" => "SCV",
		"name" => "Vale",
		"price" => 7.50,
		"parent" => "Shade Card",
		"type" => "Shade Card",
	),
	array(
		"sku" => "CAP01",
		"parent" => "CAPSULE",
		"name" => "Olga Buraya-Kefelian",
		"price" => 15,
		"type" => "Books + E-Books",
	),
	array(
		"sku" => "CAP02",
		"parent" => "CAPSULE",
		"name" => "Michele Wang",
		"price" => 15,
		"type" => "Books + E-Books",
	),
	array(
		"sku" => "JJF01",
		"parent" => "WOOLENS",
		"name" => "Jared Flood",
		"price" => 15,
		"type" => "Books + E-Books",
		"qty" => "",
	),
	array(
		"sku" => "CARD01",
		"parent" => "SWEATER CARDS",
		"name" => "Limited Edition Watercolor",
		"price" => 10,
		"type" => "Gift Card",
	),
	array(
		"sku" => "P001",
		"name" => "Alberta",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P002",
		"name" => "Autumn Leaves Stole",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P003",
		"name" => "Beaumont",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P005",
		"name" => "Brownstone",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P006",
		"name" => "Celes",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P007",
		"name" => "Cinder",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P008",
		"name" => "Cobblestone",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P009",
		"name" => "Dryad",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P010",
		"name" => "Fenimore",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P011",
		"name" => "Fortnight",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P013",
		"name" => "Grove",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P014",
		"name" => "Habitat",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P016",
		"name" => "Koolhaas",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P017",
		"name" => "Metropolitan",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P018",
		"name" => "Pavement",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P019",
		"name" => "Porom",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P020",
		"name" => "Ptarmigan",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P021",
		"name" => "Quincy",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P023",
		"name" => "Rockaway",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P024",
		"name" => "Romney Kerchief",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P025",
		"name" => "Seneca",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P026",
		"name" => "Setzer",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P027",
		"name" => "Shale Baby Blanket",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P028",
		"name" => "Stilwell",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P029",
		"name" => "Turn a Square",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P030",
		"name" => "Tweed Baby Blanket",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P031",
		"name" => "Umaro",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P032",
		"name" => "Wayfarer",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P033",
		"name" => "Wee Levenwick",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P034",
		"name" => "Woodruff",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P035",
		"name" => "Wool Leaves",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P036",
		"name" => "Acadia",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P037",
		"name" => "Allegheny",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P038",
		"name" => "Caldwell",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P039",
		"name" => "Cyklon",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P040",
		"name" => "Holl",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P041",
		"name" => "Hourglass",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P042",
		"name" => "Levenwick",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P043",
		"name" => "Perry",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P044",
		"name" => "Quinnipiac",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P045",
		"name" => "Seraphine",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P046",
		"name" => "Shadow",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P047",
		"name" => "Shipyard",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P048",
		"name" => "St. Leger",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P049",
		"name" => "Sullivan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P050",
		"name" => "Vega",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P051",
		"name" => "Ashby",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P052",
		"name" => "Bedford",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P053",
		"name" => "Broome",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P054",
		"name" => "Flint",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P055",
		"name" => "Huxley",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P056",
		"name" => "Irving",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P057",
		"name" => "Lockhart",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P058",
		"name" => "Muir",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P059",
		"name" => "Nero",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P060",
		"name" => "Ninian",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P061",
		"name" => "Peabody",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P062",
		"name" => "Ranger",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P063",
		"name" => "Rosebud",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P064",
		"name" => "Tinder",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P065",
		"name" => "Topiary",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P066",
		"name" => "Burnham",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P067",
		"name" => "Carlisle",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P068",
		"name" => "Edie",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P069",
		"name" => "Farthing",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P070",
		"name" => "Jaffrey",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P071",
		"name" => "Leaves of Grass",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P072",
		"name" => "Parson",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P073",
		"name" => "Pei",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P074",
		"name" => "Permafrost",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P075",
		"name" => "Sakura",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P076",
		"name" => "Spire",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P077",
		"name" => "Stonecrop",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P078",
		"name" => "Thayer",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P079",
		"name" => "Wexford",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P080",
		"name" => "34th & 8th",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P081",
		"name" => "Arrowhead",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P082",
		"name" => "Ash",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P083",
		"name" => "Clemence",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P084",
		"name" => "Elfreide",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P085",
		"name" => "Fuse",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P086",
		"name" => "Graham",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P087",
		"name" => "Guston",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P088",
		"name" => "Kendrick",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P089",
		"name" => "Lawrence",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P090",
		"name" => "Norby",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P091",
		"name" => "Spruce Forest",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P092",
		"name" => "Trace",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P093",
		"name" => "Winnowing",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P094",
		"name" => "Barrington",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P095",
		"name" => "Chinook",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P096",
		"name" => "Convoy",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P097",
		"name" => "Exeter",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P098",
		"name" => "Forester",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P099",
		"name" => "Gloaming",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P100",
		"name" => "Hege",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P101",
		"name" => "Inversion",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P102",
		"name" => "Kildare",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P103",
		"name" => "Oslo",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P104",
		"name" => "Polar",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P105",
		"name" => "Quill",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P106",
		"name" => "Ravensfoot",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P107",
		"name" => "Seasons",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P108",
		"name" => "Stasis",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P109",
		"name" => "Sweetgrass",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P110",
		"name" => "Talon",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P111",
		"name" => "Ando",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P112",
		"name" => "Auden",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P113",
		"name" => "Bayard",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P114",
		"name" => "Biston",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P115",
		"name" => "Boardwalk",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P116",
		"name" => "Breckon",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P117",
		"name" => "Corrina",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P118",
		"name" => "Edge",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P119",
		"name" => "Ferrous Wrap",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P120",
		"name" => "Fjord",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P121",
		"name" => "Haru-Gasumi",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P122",
		"name" => "Oljett",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P123",
		"name" => "Reine",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P124",
		"name" => "Rivage",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P125",
		"name" => "Themis",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P126",
		"name" => "Ticking",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P127",
		"name" => "Walpole",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P128",
		"name" => "Anais",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P129",
		"name" => "Bowen",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P130",
		"name" => "Breton",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P131",
		"name" => "Burr",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P132",
		"name" => "Driftwood",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P133",
		"name" => "Emery",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P134",
		"name" => "Eternity Cardigan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P135",
		"name" => "Eternity Scarf",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P136",
		"name" => "Fade",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P137",
		"name" => "Fairfield",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P138",
		"name" => "Gelsomina Aran",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P139",
		"name" => "Gelsomina Wristwarmers",
		"price" => 3,
		"type" => "Pattern",
	),
	array(
		"sku" => "P140",
		"name" => "Guilder",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P141",
		"name" => "Hayward",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P142",
		"name" => "Sempervivum",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P143",
		"name" => "Turnagain",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P144",
		"name" => "Wellwood",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P145",
		"name" => "Benedetta",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P146",
		"name" => "Chicane",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P147",
		"name" => "Dresden Vest",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P148",
		"name" => "Hathaway",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P149",
		"name" => "Inglenook",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P150",
		"name" => "Kenzo",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P151",
		"name" => "Kindling",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P152",
		"name" => "Lumen",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P153",
		"name" => "Macallan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P154",
		"name" => "Runa",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P155",
		"name" => "Scrollwork",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P156",
		"name" => "Stranger",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P157",
		"name" => "Thorn",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P158",
		"name" => "Tilda",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P159",
		"name" => "Vertex",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P160",
		"name" => "Adara",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P161",
		"name" => "Altair",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P162",
		"name" => "Clayton",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P163",
		"name" => "Cypress",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P164",
		"name" => "Grettir",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P165",
		"name" => "Guernsey Triangle",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P166",
		"name" => "Hellebore",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P167",
		"name" => "Hudson",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P168",
		"name" => "Ives",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P169",
		"name" => "Kimmswick",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P170",
		"name" => "Kirkwood",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P171",
		"name" => "Knoll",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P172",
		"name" => "Pinion",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P173",
		"name" => "Snowflake Stole",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P174",
		"name" => "Stowe",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P175",
		"name" => "Tuck",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P176",
		"name" => "Warren Street Cowl",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P177",
		"name" => "Waterhouse",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P178",
		"name" => "Amherst",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P179",
		"name" => "Asilomar",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P180",
		"name" => "Bolt",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P181",
		"name" => "Fleur",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P182",
		"name" => "Flying Squirrel",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P183",
		"name" => "Frida",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P184",
		"name" => "Hitch",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P185",
		"name" => "Kennebec",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P186",
		"name" => "Lira",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P187",
		"name" => "Moon & Stars",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P188",
		"name" => "Reverb",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P189",
		"name" => "Sandness",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P190",
		"name" => "Sandycove",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P191",
		"name" => "Stones & Stripes",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P192",
		"name" => "Tilt",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P193",
		"name" => "Wheaten",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P194",
		"name" => "Barrett",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P195",
		"name" => "Brig",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P196",
		"name" => "Chesterfield",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P197",
		"name" => "Eno",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P198",
		"name" => "Fort",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P199",
		"name" => "Hayes",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P200",
		"name" => "Hugo",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P201",
		"name" => "Janzen",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P202",
		"name" => "Quay",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P203",
		"name" => "Redford",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P204",
		"name" => "Slade",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P205",
		"name" => "Squall",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P206",
		"name" => "Timberline",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"sku" => "P207",
		"name" => "Afton",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P208",
		"name" => "Archer",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P209",
		"name" => "Bray Cap",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P210",
		"name" => "Bray Pullover",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P211",
		"name" => "Coal Cardigan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P212",
		"name" => "Feather",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P213",
		"name" => "Hartford",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P214",
		"name" => "Idlewild",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P215",
		"name" => "Jules",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P216",
		"name" => "Oshima",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P217",
		"name" => "Stonecutter",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P218",
		"name" => "Tread",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P219",
		"name" => "Trillium",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P220",
		"name" => "Vale",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P221",
		"name" => "Bough",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P222",
		"name" => "Brigitte",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P223",
		"name" => "Carpino",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P224",
		"name" => "Ceridwen",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P225",
		"name" => "Gentian",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P226",
		"name" => "Greenwood",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P227",
		"name" => "Little Wave",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P228",
		"name" => "Persimmon",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P229",
		"name" => "Rook",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P230",
		"name" => "Sundottir",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P231",
		"name" => "Svalbard",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P232",
		"name" => "Tree Rings",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P233",
		"name" => "Trestle",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P234",
		"name" => "Abbott",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P235",
		"name" => "Alloy",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P236",
		"name" => "Benton",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P237",
		"name" => "Channel Cardigan",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P238",
		"name" => "Echelon",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P239",
		"name" => "Elmont",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P240",
		"name" => "Frieze",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P241",
		"name" => "Hickory Cap",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P242",
		"name" => "Kelpie",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P243",
		"name" => "Landfall",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P244",
		"name" => "Montauk",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P245",
		"name" => "Nord",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P246",
		"name" => "Portis",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P247",
		"name" => "Thicket",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P248",
		"name" => "Walsh",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P249",
		"name" => "Arabella",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P250",
		"name" => "Arvid",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P251",
		"name" => "Coda",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P252",
		"name" => "Devlan",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P253",
		"name" => "Halligarth",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P254",
		"name" => "Hoquiam",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P255",
		"name" => "Ivar",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P256",
		"name" => "Merle",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P257",
		"name" => "Natsumi",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P258",
		"name" => "Nimbus",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P259",
		"name" => "Pente",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P260",
		"name" => "Seacoast",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P261",
		"name" => "Seine",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P262",
		"name" => "Vector",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P263",
		"name" => "Yane",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P264",
		"name" => "Arlo",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P265",
		"name" => "Atlas",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P266",
		"name" => "Bairn",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P267",
		"name" => "Berenice",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P268",
		"name" => "Carson",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P269",
		"name" => "Humphrey",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P270",
		"name" => "Husk",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P271",
		"name" => "Magnus",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P272",
		"name" => "Petal",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P273",
		"name" => "Pinwheel",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P274",
		"name" => "Sock Monkey",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P275",
		"name" => "Spore",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P276",
		"name" => "Vika",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P277",
		"name" => "Winslow",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P278",
		"name" => "Wyatt",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P279",
		"name" => "Backbay",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P280",
		"name" => "Bellows",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P281",
		"name" => "Crosby",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P282",
		"name" => "Docklight",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P283",
		"name" => "Furl",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P284",
		"name" => "Hawser",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P285",
		"name" => "Hutchin",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P286",
		"name" => "Ludlow",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P287",
		"name" => "Ondawa",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P288",
		"name" => "Rowe",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P289",
		"name" => "Shackleton",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P290",
		"name" => "Skiff",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P291",
		"name" => "Spinnaker",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P292",
		"name" => "Tiller",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P293",
		"name" => "Wake",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P294",
		"name" => "Zenith",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P295",
		"name" => "Aster",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P296",
		"name" => "Bracondale",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P297",
		"name" => "Cedarwood",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P298",
		"name" => "Corbara",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P299",
		"name" => "Eaves",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P300",
		"name" => "Escher",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P301",
		"name" => "Field",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P302",
		"name" => "Flight",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P303",
		"name" => "Gable",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P304",
		"name" => "Keel",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P305",
		"name" => "Maurits",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P306",
		"name" => "Millisande",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P307",
		"name" => "Rambler",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P308",
		"name" => "Sawmill River",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P309",
		"name" => "Skew",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P310",
		"name" => "Stratum",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P311",
		"name" => "Woodfords",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P312",
		"name" => "Agnes",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P313",
		"name" => "Alvy",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P314",
		"name" => "Carpeaux",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P315",
		"name" => "Chainlink",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P316",
		"name" => "Cordova",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P317",
		"name" => "Emerson",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P318",
		"name" => "Harper",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P319",
		"name" => "Keaton",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P320",
		"name" => "Kusama",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P321",
		"name" => "Lexington",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P322",
		"name" => "Marshal",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P323",
		"name" => "Midway",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P324",
		"name" => "Nomad",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P325",
		"name" => "Sanford",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P326",
		"name" => "Shui-Mo",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P327",
		"name" => "Tapestry",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P328",
		"name" => "Yishu",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P329",
		"name" => "Albion",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P330",
		"name" => "Bradbury",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P331",
		"name" => "Carbon",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P332",
		"name" => "Crag",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P333",
		"name" => "Denali",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P334",
		"name" => "Dunaway",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P335",
		"name" => "Jackdaw",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P336",
		"name" => "Longfellow",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P337",
		"name" => "Oshima (for Him",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P338",
		"name" => "Rift",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"sku" => "P339",
		"name" => "Sawyer",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P340",
		"name" => "Shield",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P341",
		"name" => "Snare",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P342",
		"name" => "Anisos",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P343",
		"name" => "Arbre",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P344",
		"name" => "Element",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P345",
		"name" => "Gehry",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P346",
		"name" => "Grille",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P347",
		"name" => "Gyre",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P348",
		"name" => "Imago",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P349",
		"name" => "Kea",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P350",
		"name" => "Koto",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P351",
		"name" => "Loden",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P352",
		"name" => "Mimic",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P353",
		"name" => "Mirepoix",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P354",
		"name" => "Rakke",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P355",
		"name" => "Truss",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P356",
		"name" => "Ashland",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P357",
		"name" => "Bannock",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P358",
		"name" => "Birch Bay",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P359",
		"name" => "Cascades",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P360",
		"name" => "Copse",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P361",
		"name" => "Deschutes",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P362",
		"name" => "Fletching",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P363",
		"name" => "Lander",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P364",
		"name" => "Lolo",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P365",
		"name" => "McLoughlin",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P366",
		"name" => "Nehalem",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P367",
		"name" => "Riverbend",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P368",
		"name" => "Sauvie",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P369",
		"name" => "Trailhead",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P370",
		"name" => "Willamette",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P371",
		"name" => "Bauhin",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P372",
		"name" => "Breaker",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P373",
		"name" => "Cadence",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P374",
		"name" => "Corvid",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P375",
		"name" => "Halus",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P376",
		"name" => "Intersect",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P377",
		"name" => "League",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P378",
		"name" => "Lohman",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P380",
		"name" => "Oxbow",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P381",
		"name" => "Riptide",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P382",
		"name" => "Roslyn",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P383",
		"name" => "Selune",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P384",
		"name" => "Snoqualmie",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P385",
		"name" => "Tallis",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P386",
		"name" => "Vela",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P387",
		"name" => "Breslin",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P388",
		"name" => "Caspian",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P389",
		"name" => "Fairweather",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P390",
		"name" => "Forge",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P391",
		"name" => "Larus",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P392",
		"name" => "Vanora",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P393",
		"name" => "Amarilli",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P394",
		"name" => "Aquinnah",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P395",
		"name" => "Bronwyn",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"sku" => "P396",
		"name" => "Haro",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P397",
		"name" => "Kierson",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P398",
		"name" => "Loess",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P399",
		"name" => "Lorient",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P400",
		"name" => "Lunette",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P401",
		"name" => "Marylebone",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P402",
		"name" => "Migration",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P403",
		"name" => "Oda",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P404",
		"name" => "Rigel",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P405",
		"name" => "Saiph",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P406",
		"name" => "Scalene",
		"price" => 4,
		"type" => "Pattern",
	),
	array(
		"sku" => "P407",
		"name" => "Valemont",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P408",
		"name" => "Auster - Men\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P409",
		"name" => "Auster - Women’s",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P410",
		"name" => "Brighton - Men\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P411",
		"name" => "Brighton - Women\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P412",
		"name" => "Carver - Men\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P413",
		"name" => "Carver - Women’s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P414",
		"name" => "Cricket - Men\'s",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P415",
		"name" => "Cricket - Women\'s",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P416",
		"name" => "Mawson",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P417",
		"name" => "Mohr - Men\'s",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P418",
		"name" => "Mohr - Women\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P419",
		"name" => "Pavo",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P420",
		"name" => "Spearheads",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P421",
		"name" => "Tamarack - Men’s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P422",
		"name" => "Tamarack - Women\'s",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P423",
		"name" => "Vika (for Adults",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P424",
		"name" => "Burnaby Hat",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P425",
		"name" => "Burnaby Shawl",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P426",
		"name" => "Foundry",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P427",
		"name" => "Guernsey Wrap",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P428",
		"name" => "High Pines Cowl",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P429",
		"name" => "Hirombe",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P430",
		"name" => "Junction",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P431",
		"name" => "Laurel",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P432",
		"name" => "Terra",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P433",
		"name" => "Binary",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P434",
		"name" => "Counterpane",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"sku" => "P435",
		"name" => "Hilt",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P436",
		"name" => "Kirwin",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P437",
		"name" => "Lancet",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P438",
		"name" => "Mei",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P439",
		"name" => "Nila",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P440",
		"name" => "Oban",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P441",
		"name" => "Prime",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P442",
		"name" => "Proof Hat",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P443",
		"name" => "Proof Scarf",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P444",
		"name" => "Rivage Coat",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P445",
		"name" => "Shoji",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P446",
		"name" => "Stonehaven",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P447",
		"name" => "Svenson",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"sku" => "P448",
		"name" => "Toulouse",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P449",
		"name" => "Atlas",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P450",
		"name" => "Frostpeak",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"sku" => "P451",
		"name" => "Morse",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P452",
		"name" => "Pyry",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P453",
		"name" => "Schulz",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P454",
		"name" => "Townes",
		"price" => 8,
		"type" => "Pattern",
	),
	array(
		"sku" => "P455",
		"name" => "Tundra",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P456",
		"name" => "Bridgewater",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P457",
		"name" => "Girasole",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P458",
		"name" => "Lucca",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P459",
		"name" => "Rock Island",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P460",
		"name" => "Juneberry",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P461",
		"name" => "Gully (available July 1",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P462",
		"name" => "Akiko",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P463",
		"name" => "Bell",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P464",
		"name" => "Boundary",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P465",
		"name" => "Divide",
		"price" => 12,
		"type" => "Pattern",
	),
	array(
		"sku" => "P466",
		"name" => "Harlowe",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P467",
		"name" => "Leadlight",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P468",
		"name" => "Level",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P469",
		"name" => "Mossbank",
		"price" => 7,
		"type" => "Pattern",
	),
	array(
		"sku" => "P470",
		"name" => "Prism",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P471",
		"name" => "Ravine",
		"price" => 5,
		"type" => "Pattern",
	),
	array(
		"sku" => "P472",
		"name" => "Rivet",
		"price" => 6,
		"type" => "Pattern",
	),
	array(
		"sku" => "P473",
		"name" => "Ronan",
		"price" => 6,
		"type" => "Pattern",
	),
);
